/*******************************************************************************
 * Copyright 2018 T145
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************/
package T145.metalchests.core;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import T145.metalchests.api.BlocksMetalChests;
import T145.metalchests.api.ItemsMetalChests;
import T145.metalchests.api.ModSupport;
import T145.metalchests.api.immutable.ChestType;
import T145.metalchests.api.immutable.ChestUpgrade;
import T145.metalchests.core.proxies.CommonProxy;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.ItemStack;
import net.minecraft.util.NonNullList;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@Mod(modid = MetalChests.MOD_ID, name = MetalChests.MOD_NAME, version = MetalChests.VERSION, updateJSON = MetalChests.UPDATE_JSON, dependencies = "after:thaumcraft;after:refinedrelocation")
public class MetalChests {

	public static final String MOD_ID = "metalchests";
	public static final String MOD_NAME = "MetalChests";

	static final String VERSION = "@VERSION@";
	static final String UPDATE_JSON = "https://raw.githubusercontent.com/T145/metalchests/master/update.json";

	private static final String COMMON_PROXY = "T145.metalchests.core.proxies.CommonProxy";
	private static final String CLIENT_PROXY = "T145.metalchests.core.proxies.ClientProxy";

	public static final Logger LOG = LogManager.getLogger(MOD_ID);

	public static final CreativeTabs TAB = new CreativeTabs(MOD_ID) {

		@Override
		@SideOnly(Side.CLIENT)
		public boolean hasSearchBar() {
			return true;
		}

		@Override
		@SideOnly(Side.CLIENT)
		public ItemStack createIcon() {
			return new ItemStack(BlocksMetalChests.METAL_CHEST, 1, 1);
		}

		@SideOnly(Side.CLIENT)
		public void displayAllRelevantItems(NonNullList<ItemStack> items) {
			for (ChestType type : ChestType.values()) {
				items.add(new ItemStack(BlocksMetalChests.METAL_CHEST, 1, type.ordinal()));
			}

			for (ChestUpgrade type : ChestUpgrade.values()) {
				items.add(new ItemStack(ItemsMetalChests.CHEST_UPGRADE, 1, type.ordinal()));
			}

			if (ModSupport.hasThaumcraft()) {
				for (ChestType type : ChestType.values()) {
					items.add(new ItemStack(BlocksMetalChests.HUNGRY_METAL_CHEST, 1, type.ordinal()));
				}

				for (ChestUpgrade type : ChestUpgrade.values()) {
					items.add(new ItemStack(ItemsMetalChests.HUNGRY_CHEST_UPGRADE, 1, type.ordinal()));
				}
			}

			if (ModSupport.hasRefinedRelocation()) {
				for (ChestType type : ChestType.values()) {
					items.add(new ItemStack(BlocksMetalChests.SORTING_METAL_CHEST, 1, type.ordinal()));
				}
			}

			if (ModSupport.hasRefinedRelocation() && ModSupport.hasThaumcraft()) {
				for (ChestType type : ChestType.values()) {
					items.add(new ItemStack(BlocksMetalChests.SORTING_HUNGRY_METAL_CHEST, 1, type.ordinal()));
				}
			}

			for (ChestType type : ChestType.values()) {
				items.add(new ItemStack(ItemsMetalChests.MINECART_METAL_CHEST, 1, type.ordinal()));
			}
		}
	}.setBackgroundImageName("item_search.png");

	@Instance(MOD_ID)
	public static MetalChests instance;

	@SidedProxy(serverSide = COMMON_PROXY, clientSide = CLIENT_PROXY)
	public static CommonProxy proxy;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata meta = event.getModMetadata();
		meta.authorList.add("T145");
		meta.autogenerated = false;
		meta.credits = "The fans!";
		meta.description = "The better alternative to IronChests";
		meta.logoFile = "logo.png";
		meta.modId = MOD_ID;
		meta.name = MOD_NAME;
		meta.url = "https://github.com/T145/metalchests";
		meta.useDependencyInformation = false;
		meta.version = VERSION;
		proxy.preInit(event);
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		proxy.init(event);
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		proxy.postInit(event);
	}
}
